### ISSUE TITLE
Création de page : impossible de finaliser le formulaire.

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#100]

**Comment by yunai39** [comment]
J'ai besoin de plus de details, ou au moins d'un screen shot

**Comment by mxchrles** [comment]
Tu as réussie à régler le bug ? Ou je demande le screen ?

**Comment by yunai39** [comment]
non c'est bon

2017-11-20 20:48 GMT+01:00 mxchrles <notifications@github.com>:
