### ISSUE TITLE
Deux fois la même page à la création

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#104]
Une page a été deux fois créées, pouvoir supprimer une page à partir de l'admin. 
![image](https://user-images.githubusercontent.com/20457917/33016197-d95477e2-cded-11e7-9ba3-57dd294dfe33.png)

**Comment by yunai39** [comment]
Idem si ca le fait une fois c'est que quelqu'un a cliquer en double, est je donnerai probablement pas la possibiliter de supprimer un page, il faudrait plutot que j'ajoute la possibilite de la desactiver

**Comment by mxchrles** [comment]
Oui voilà c'est ça, pouvoir la désactiver ! ^^
