### ISSUE TITLE
Certains ne reçoient pas de mails

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#106]
Comme le cas de Lancelot, j'ai activé son compte manuellement

**Comment by yunai39** [comment]
Si y en a une qui les recoits il doivent tous les recevoir, apres y a de grand chance qu'on soit considerer comme du spam etant donner que je passe pas par un vrai serveur de mail

**Comment by yunai39** [comment]
L'adresse email de lancelot ne devait pas etre bonne dans le compte gmail j'ai recu une notification


Message non distribuéUn problème est survenu lors de la distribution de votre message à lancelot.duquesnoy@sfr.fr. Consultez les informations techniques ci-dessous. | Message non distribuéUn problème est survenu lors de la distribution de votre message à lancelot.duquesnoy@sfr.fr. Consultez les informations techniques ci-dessous. | Message non distribué | Un problème est survenu lors de la distribution de votre message à lancelot.duquesnoy@sfr.fr. Consultez les informations techniques ci-dessous.
-- | -- | -- | --
Message non distribuéUn problème est survenu lors de la distribution de votre message à lancelot.duquesnoy@sfr.fr. Consultez les informations techniques ci-dessous. | Message non distribué | Un problème est survenu lors de la distribution de votre message à lancelot.duquesnoy@sfr.fr. Consultez les informations techniques ci-dessous.
Message non distribué
Un problème est survenu lors de la distribution de votre message à lancelot.duquesnoy@sfr.fr. Consultez les informations techniques ci-dessous.
Réponse du serveur distant :550 5.7.1 Message content rejected
