### ISSUE TITLE
[Suggestion] Suppression de photo dans l'administration

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#11]
En cliquant sur "Supprimer cette photo" et une fois les modifications validées, les photos ne sont pas supprimées. Comme indiqué, il faut cocher la case qui permet cela. Suggestion: supprimer le lien qui fait supprimer les photos pour éviter toute confusion.

**Comment by yunai39** [comment]
Je close le truc, parce aue je peux pas vraiment le controller vu qu'on passe par easy admin
