### ISSUE TITLE
Bouton "afficher plus" des publications a disparût sur les dépêches magiques

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#116]

**Comment by yunai39** [comment]
Sur quel page exactement ? Je vois toujours le bouton personnelement ?

**Comment by mxchrles** [comment]
Sur la page "dépêches magiques" quand je suis connecté :)

**Comment by yunai39** [comment]
Fais moi un screen, j'ai un bouton afficher dans tous les cas

**Comment by yunai39** [comment]
En fait il a jamais existé ^^
