### ISSUE TITLE
[Bug] Affichage du caroussel en l'absence de photo

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#12]
Après avoir supprimé les photos de la publication, le carrousel n'a pas disparût. J'ai d'ailleurs une suggestion, qui est tout simplement de supprimer le carrousel et d'afficher les photos à la suite des autres, comme sur Medium. Plus pratique sur mobile et plus "littéraire". Dommage, je l'aimais bien !

**Comment by yunai39** [comment]
Corrige
