### ISSUE TITLE
[Bug] Affichage des publications sur le profil

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#13]
En allant sur le profil de l'admin, les publications des personnes avec qui il est amis étaient affichées.
Suggestions:
- Afficher sur le profil les publications de la personne dont il est le sujet uniquement.

**Comment by yunai39** [comment]
C'est quel page exactement tu peux me refiler l'url

**Comment by mxchrles** [comment]
Celui-ci: http://wizardsalley.ddns.net:8888/user/wall/display/2 :)

**Comment by yunai39** [comment]
Ok normalement j'ai corrigé tu peux reverifier ?

**Comment by mxchrles** [comment]
Du coup là ce sont mes publications à moi et non celles de l'admin ^^

**Comment by yunai39** [comment]
Ok donc c'est corriger, sur la page de wall on affiche que les publications de l'utilisateur du wall, sur la page profile que les publications d el'utilisateur en cours et sur le ruelle les publication des amis, des pages qu'on suit et nos publications
