### ISSUE TITLE
[Bug/Suggestion] Affichage des publications au nom de la page et non de l'éditeur

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#14]
Il peut-être confus de savoir qui a publié le message: au nom de la page ou au nom de la personne ? Du coup je suggère d'afficher l'image de la page à la place de l'image de profil de l'utilisateur, mais éventuellement de mettre une annotation en fin avec écrit "Publié par @truc".

**Comment by yunai39** [comment]
C'est bon
