### ISSUE TITLE
[Bug] On peut aimer une page à plusieurs reprises

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#16]
J'ai pu aimer la page de l'équipe à plusieurs reprises, j'apparaîs d'ailleurs deux fois dans les followers.

**Comment by yunai39** [comment]
Ok normalement je viens de corriger tu peux re-tester ? J'ai supprimer tous les likes.

**Comment by mxchrles** [comment]
Oui, c'est bon ! 👯‍♂️
