### ISSUE TITLE
[Suggestion] Déplacement des liens inscription/Connexion

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#27]
La barre de navigation fait bien vide avec uniquement deux liens quand on est pas connecté, du coup est-ce que ce serait possible de transférer les liens comme sur la maquette et ajouter pour l'occasion de lien "Blog de l'équipe" ? :)

Voir ici: http://thewizardsalley.com/center/private/concept/s3/

**Comment by yunai39** [comment]
Ouais pas de probleme par contre c'est quoi le lien du blog ?

**Comment by mxchrles** [comment]
C'est "https://blog.thewizardsalley.com" :)

**Comment by yunai39** [comment]
C'est bon
