### ISSUE TITLE
[Dev] Ajouter deux class dans les publications

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#29]
Pour que je puisse donner un style différent au nom de l'utilisateur/page, à la date et au texte de la publication, j'aimerais savoir si tu pouvais ajouter une class "publication-author" au lien de l'auteur, une class "publication-date" à la date ? :)

**Comment by yunai39** [comment]
C'est bon !!

**Comment by mxchrles** [comment]
Merci beaucoup :)
