### ISSUE TITLE
[Corrections grammaticales]

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#30]
**Accueil/Footer**
NotificationS
SorcierS en ligne
MentionS LégaleS
**Discover**
CatégorieS
(Supprimer catégorie: avant le nom de la catégorie)
**Profils**
Page(S) Crée(S) (met les "S" entre parenthèses)
Page rédacteur > Plutôt "Auteur sur"

**Comment by yunai39** [comment]
Pour l'orthographe, comme je te l'avais dit je suis nul, du coup si tu a des corrections d'orthographe, c'est tous dans un fichier. dans app/Resources/translations/messages.fr.yml

**Comment by mxchrles** [comment]
Ah super, merci beaucoup ! C'est parfait, je me demandais où on modifiait ça !
C'est aussi dans ce document qu'on donne le titres des pages dans les onglets ? :)

**Comment by yunai39** [comment]
Nope ca j'ai pas encore fait, mais oui tu peux preparer tous les traductions et je les ajouterais apres

**Comment by mxchrles** [comment]
D'accord pas de soucis :)
