### ISSUE TITLE
[Dev] Apporter class "profil" (par exemple) sur les body des profils

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#35]
J'ai réduit la taille des head sur les différentes page pour l'ergonomie du site, pour gagner en espace. Cependant, ça ne laisse pas assez de place pour afficher le contenu sur les profils. Tu pourrais donc ajouter une classe au body des profils de manière à donner un height plus élevé aux head des profils ? :)

**Comment by yunai39** [comment]
Ok j'ai ajouter les class head-profile sur la page de profile et de wall, pour ajouter une class a la div head depuis un page c'est pas trop complique tu ajout ca

`{% block head_extra_class %}head-page{% endblock %}`
