### ISSUE TITLE
[Suggestion] Class pour les profils "head"

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#40]
- Le "head" (la partie avec la cover etc) sur les profils (wall etc) ajouter une classe spécifique pour gérer spécifiquement la hauteur de la partie
- Faire pareil sur les pages 
- EDIT: faire pareil sur la page discover non connecté, et mettre le texte "Bienvenue amis sorciers sur le portail magique de l'Allée des Sorciers."

**Comment by yunai39** [comment]
sur profile et wall tu as une class head-profile
sur les pages tu as la class head-page
sur les category head-category
head-confidentiality
head-contact
head-copyright
head-discover
head-mention
head-search
head-map
head-notification
head-user-home
