### ISSUE TITLE
Harmonisation des publications

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#53]
Voici à quoi ressemblent les publications à l'heure actuelle.

Sur la page "Ma ruelle" et sur les "Dépêches magiques":
![image](https://user-images.githubusercontent.com/20457917/30853910-69aa3656-a2b0-11e7-9723-5f6a70ef5b17.png)

Une fois la publication affichée dans son ensemble:
![image](https://user-images.githubusercontent.com/20457917/30853956-872b2802-a2b0-11e7-93b8-78c2d964765b.png)

Idem pour les publications des pages. Pour ne pas perdre l'utilisateur entre chacunes des pages, je propose une harmonisation de l'affichage des publications de cette manière, et n'importe où se trouve la publication:

![publication](https://user-images.githubusercontent.com/20457917/30854007-ae85a346-a2b0-11e7-9bbd-4257daf5255e.png)

Si tu veux une sorte de schéma:

![publication schema](https://user-images.githubusercontent.com/20457917/30854018-b80d1f84-a2b0-11e7-830e-3c6393c83a20.png)

**Comment by yunai39** [comment]
Tu refras un tour j'ai fait des modifications

**Comment by mxchrles** [comment]
Tu pourrais faire l'update sur le site pour que je puisse voir, en local ça bug je ne vois aucune publication :(
