### ISSUE TITLE
[Concept] Nouvelle messagerie

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#57]
Voilà un concept art pour la nouvelle messagerie !
![image](https://user-images.githubusercontent.com/20457917/30909094-2c5df672-a380-11e7-91c1-61bd98390ae9.png)

Tu peux aller voir ici: http://thewizardsalley.com/center/private/concept/s3/messenger/ :)

**Comment by yunai39** [comment]
C'est bon !! Et j'ai ajouter des class css pour faire le rendu
