### ISSUE TITLE
[Modifications / ajouts] Page inscription et connexion

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#58]
Peux-tu mettre le texte

"(p)Se connecter(p)
(h2)Bienvenue sorcier, sorcière en tout genre. Prends un peu de poudre de cheminette et prononce clairement "Wizard's Alley" (/h2)"

Dans la partie header (c'est à dire à la place de "Dépêches favorites etc") et mettre à cet endroit le background avec le train ?

Idem pour la page d'inscription avec en texte
(p)S'inscrire(p)
(h2)Bienvenue sorcier, sorcière en tout genre. Prends un peu de poudre de cheminette et prononce clairement "Wizard's Alley" (/h2)"

+ Sur la page s'inscrire si tu pouvais rajouter la classe ".wizardsalley-register-form-submit" sur le bouton "s'inscrire" ? :)

Merci <3

**Comment by yunai39** [comment]
C'est bon
