### ISSUE TITLE
[Modification] Quelques arrangements dans le code

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#59]
Coucou, voilà quelques arrangements pour le code. Il y a des modifications dont j'ai besoin de faire sur des points précis.

- Peux-tu supprimer les "Content" au dessus des champs d'entrée de message ?
- Peux-tu ajouter la class "profil-infos" (sur les pages et profil) à cette partie:
![image](https://user-images.githubusercontent.com/20457917/30929081-ac381eee-a3bd-11e7-85f3-0a7bf63e0a2e.png)
- Ajouter la class "profil-about" à cette partie:
![image](https://user-images.githubusercontent.com/20457917/30929100-bc78914e-a3bd-11e7-9b69-5e626a8be360.png)
- Dans la page "Dépêches magiques" ajouter la class "categories" à cette partie:
![image](https://user-images.githubusercontent.com/20457917/30929143-e1863950-a3bd-11e7-9320-197334f1443d.png)

Voilà merci <3

**Comment by yunai39** [comment]
Donc les contents c'est bon, j'ai ajouter des class profile-infos-panel, profile-about-panel et categories-panel
