### ISSUE TITLE
[Améliorations] Page de recherche

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#61]
Voilà un concept art, dis-moi ce que tu en pense :)
Tu peux voir ce que ça donne ici: http://thewizardsalley.com/center/private/concept/s3/search/
![image](https://user-images.githubusercontent.com/20457917/30957764-78cd312e-a43b-11e7-8d4e-3a9c6163d978.png)

**Comment by yunai39** [comment]
J'aime bien, je vais regarder pour faire ca

**Comment by yunai39** [comment]
Bon y a juste la partie sur les communaute magique, pour toi c'est quoi ? Les catégories ?

**Comment by mxchrles** [comment]
Les communautés magiques ce sont les pages en fait :)

**Comment by yunai39** [comment]
Ok normalement j'ai finis, par contre je suis pas chez moi donc je peux pas mettre a jour le site
