### ISSUE TITLE
[Requete] Ajout formulaire de publication sur les pages que l'on administre

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#66]
Pour ajouter des publications lorsque nous sommes éditeur sur une page. Exemple, je suis éditeur sur la page de Allée des Sorciers, donc quand je vais ici: http://wizardsalley.ddns.net:8888/page/show/1 pouvoir publier en son nom

**Comment by yunai39** [comment]
Du coup non c'est pas possible trop chiant d'ajouter le formulaire avec les inputs d'image et compagnie
