### ISSUE TITLE
[Requete] Supprimer caroussel, afficher les images à la suite dans les publications

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#69]

**Comment by yunai39** [comment]
Ok j'ai fait la modification et rajouter des class je te laisse faire le css. Tu a un wrapper (publication-image-container) pour chaque img avec l'image (publication-image-image) et un capiton (publication-image-caption)

`<div class="publication-image-container">
                                        <img class="publication-image-img img-responsive" src="/uploads/publications/11182718-540147926133617-8024696716707741294-o-55d74c74ccd7a.jpg" "="">
                                        <div class="publication-image-caption">
                                            cercle
                                        </div>
                                    </div>`
