### ISSUE TITLE
[Max] Modifications CSS

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#74]
OK - Modifier la police d'écriture sur les longues publications
OK - Modifier taille de police d'écriture (date + heure)
OK- Modifier border-bottom sur la page de navigation
- Catégorie divers etc page de couverture (faire une maquette à Marine)
OK- Footer revoir le margin autour des liens

Messagerie
ok - Revoir taille police
ok - Affichage des discutions

Notifications
ok - Police d'écriture
ok - Bouton "Marquer comme lu"

Recherche
ok - Hauteur du bouton "recherche"

Profil 
- Bouton "parcourir" etc
- Profil a été mis à jour

ok -  Maquette page de profil

**Comment by yunai39** [comment]
Euh tu veux faire quoi du coup la ?
