### ISSUE TITLE
[Requete] "Changer de mot passe" intégrer dans les profils (comme pour les commentaires etc) + Edition des pages idem avec header et colonne de droite dans les pages

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#75]

**Comment by yunai39** [comment]
Rien compris, si tu peux faire des screen shot

**Comment by mxchrles** [comment]
Dac pas de soucis !

Alors actuellement pour changer son mot de passe c'est comme ça:
![image](https://user-images.githubusercontent.com/20457917/33271668-348ed298-d388-11e7-8bfa-5b54fef90f43.png)


Et bien au lieu de mettre dépêches favorites etc, intégrer dans le profil comme lorsque nous éditons nos autres informations:

![image](https://user-images.githubusercontent.com/20457917/33271713-52e7e23e-d388-11e7-8a77-ff1eb837398f.png)

**Comment by mxchrles** [comment]
Idem pour les pages, tout ce qui est "Edition de la page" etc:
![image](https://user-images.githubusercontent.com/20457917/33271788-7d1f4db2-d388-11e7-95b4-a7ed7b563ed3.png)

Ajouter au menu général sur le côté:
![image](https://user-images.githubusercontent.com/20457917/33271805-8c1a56ea-d388-11e7-8fcd-ce4f8af1d6ff.png)

(d'ailleurs je n'arrive pas à retirer les marges autour des liens pour aligner avec le texte)
Et le contenu des modifications:
![image](https://user-images.githubusercontent.com/20457917/33271828-a459c948-d388-11e7-8bde-c3a4f8d05124.png)

Intégrer dans le profil à la place de "Publications": 
![image](https://user-images.githubusercontent.com/20457917/33271860-baa23f0a-d388-11e7-99b5-6d0109690adf.png)

**Comment by mxchrles** [comment]
Pareil, tout ce qui est modifier/administrer la page, mettre un titre "Modifier les informations de la page" comme ce que nous faisons avec les profils:
![image](https://user-images.githubusercontent.com/20457917/33271916-e21f8cfe-d388-11e7-8104-23c07ec2cd95.png)

**Comment by mxchrles** [comment]
Pareil du coup pour créer une nouvelle page :) http://wizardsalley.ddns.net:8888/user/page/new
