### ISSUE TITLE
[Bug] Ajout d'une catégorie dans admin

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#80]
"An exception occurred while executing 'INSERT INTO page_category (name, description, logo, updated_at) VALUES (?, ?, ?, ?)' with params ["Sites dactualites", "test", null, null]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'logo' cannot be null"

**Comment by yunai39** [comment]
Corrige !!
