### ISSUE TITLE
[Bug] Affichage d'une publication à la suite d'une notification

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#87]
Je viens de publier un article sur la page de Wizard's Alley.
J'ai alors reçu une notification:

![image](https://user-images.githubusercontent.com/20457917/32442791-ed42d47a-c2fc-11e7-9692-d34159ad3a18.png)

Voilà ce que j'ai en cliquant sur le lien:

![unknown](https://user-images.githubusercontent.com/20457917/32442747-c6051a62-c2fc-11e7-94a2-b1da093541f7.png)

**Comment by yunai39** [comment]
C'est bon c'est corriger. La publication exist mais elle était pas visible, du coup maintenant, les notifications partiront pas au moment de la creation d'une publication mais a sa mise en ligne et seulement si elle n'a jamais ete publiée.
