### ISSUE TITLE
[Requete] Affichage des messages utilisateurs

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#92]
![unknown](https://user-images.githubusercontent.com/20457917/32703161-0f62abe4-c7f2-11e7-830f-7aa5de136b35.png)

https://media.discordapp.net/attachments/379364896455917589/379369622601990145/unknown.png
![unknown](https://user-images.githubusercontent.com/20457917/32703169-25f5e66e-c7f2-11e7-9f0d-692da05b7ba1.png)

**Comment by yunai39** [comment]
C'est bon j'ai repris la meme structure
