### ISSUE TITLE
Corrections multiples de la charte graphique

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#93]
Coucou, il y a différents points par-ci par-là que j'ai essayé de corriger comme je le pouvais, mais comme les modules n'ont pas de class spécifiques, mes modifications agissent à différents endroits non désirés. L'objectif de cette "Issue" est de renforcer une cohérence graphique au sain de la plateforme et régler quelques problèmes visuels et aussi dans l'expérience utilisateur.

Alors Marine, je suis sincèrement désolé car je suis plus que jamais très chiant et j'aime pas ça :(

# Listing des sorciers ou des pages
Dans toutes les pages se trouvent des listings de sorciers ou des pages. Sur la page "ma ruelle":

![image](https://user-images.githubusercontent.com/20457917/32770863-5443f346-c921-11e7-94f8-a8f5ed0006e4.png)

Dans les dépêches magiques:
![image](https://user-images.githubusercontent.com/20457917/32770902-73c0179a-c921-11e7-8d77-dcb6a0775f30.png)

Sur les profils:
![image](https://user-images.githubusercontent.com/20457917/32770949-8ef74952-c921-11e7-80ad-02e454066812.png)

Sur les pages:
![image](https://user-images.githubusercontent.com/20457917/32770982-a4cff5bc-c921-11e7-9486-b369363984c8.png)

Toutes ont la même fonction, à savoir lister des pages ou des personnes. Cependant, l'affichage et la structure n'est jamais la même. C'est pourquoi je te propose d'universaliser la structure de tout ça (en gros, faisant un block sans bug d'affichage etc et le copier sur les autres pages en apportant les spécificités). Si c'est 1) possible et 2) pas long.

La structure pourrait être (par exemple):
```
<article class="listing-peoples-pages">
<a href="/user/yunai39" class="people-page">
<img src="yunai39.jpg">
<p>Yunai39</p>
</a>
</article>
```
*A* Idem pour les pages. Celle qui est la structurée et stable est la liste "amis" sur les profils (idem pour "pages suivies"). Si tu pouvais reprendre la même structure, apporter les class que j'ai mis ci-dessus dans le code et l'appliquer sur les autres pages quand on retrouve un listing ? Pour le CSS, je verrais après !

# Profils, pages et commentaires
*B* + Sur la page des profils et des pages, si on pouvait supprimer le lien et laisser juste l'icone Facebook et Twitter ?
![image](https://user-images.githubusercontent.com/20457917/32771430-f2967d92-c922-11e7-8700-70499a79e19d.png)
*C* + Serait-il possible d'appliquer des class aux parties "Dernière connexion" et ne plus afficher les adresses mails ?
*D* + Sur les pages des profils: apporter des champs Twitter, Instagram, Youtube ?
*E* + Sur les profils et pages, afficher par défaut 3 ou 4 dernières publications ?
*Ebis* + Idem, j'ajoute quelque chose: si on pouvait mettre en page les champs de modification et d'upload des images de cette manière: https://thewizardsalley.com/center/private/concept/s3/harrypotter/edit

Sur les pages:
*F* + Centraliser tous les liens dans le aside (ajouter édition de la page, édition des publications) ?
*G* + Ajouter un lien "Ajouter une publication" au dessus des publications telles que le bouton "send" quand on envoie une petite publication ?
![image](https://user-images.githubusercontent.com/20457917/32771537-406a5d40-c923-11e7-915c-03b776d092e9.png)
*H* Sur chaque lien, apporter une class de telle sorte:
![image](https://user-images.githubusercontent.com/20457917/32771660-bc64ee9c-c923-11e7-9b8a-a7ef778c6175.png)
(pareil, pour que je puisse faire agir du css)

Dans les tableaux comme celui-ci:
![image](https://user-images.githubusercontent.com/20457917/32771717-e42c3868-c923-11e7-9967-2a90aab73076.png)
*I* + Apporter une class "table-title" à "Liste des publications" ?
*J* + Apporter une class "table-subtile" à "nombres de publications" ou d'autres trucs du genre ?

Dans les formulaires:
![image](https://user-images.githubusercontent.com/20457917/32771855-6728cc7c-c924-11e7-9bb6-9f20861d9182.png)
"Title", "image", "mot de passe"... s'affichent à droite. C'est parce que j'ai mis un text-align dans la class et du coup ça bug. 
*K* + Si tu pouvais donner aux tableaux et formulaire des class spécifiques comme par exemple "class="table-form" ?

# Parlons des boutons !
Des boutons d'action se trouvent un peu partout sur le site et n'ont pas de css particulier.

Nous avons l'upload d'image dans les publications:
![image](https://user-images.githubusercontent.com/20457917/32771956-b3f4a4fe-c924-11e7-807c-6c3fdbdc1dd5.png)

Des "mettre à jour" dans à peu près tous les formulaires:
![image](https://user-images.githubusercontent.com/20457917/32771997-d2ce119e-c924-11e7-8c5c-5af763bc7314.png)

*L* +Serait-il possible d'apporter une class spécifique à ces boutons-là (même class que "send pour les courtes publications, que pour s'inscrire, pour se connecter, mettre à jour les infos, partout où se trouve un bouton d'envoie sur le site) ?

On a presque fini !

# Amélioration ergonomique des pages:
J'ai déjà créé un sujet à ce sujet, mais je le remet ici pour bien tout centraliser ! [https://github.com/yunai39/WizardsAlley/issues/88](https://github.com/yunai39/WizardsAlley/issues/88)

# Dans la messagerie
Voici cette partie de la messagerie: 
![image](https://user-images.githubusercontent.com/20457917/32772165-59b369f2-c925-11e7-9e20-65459044069a.png)

*M* + Si tu pouvais apporter la même structure (= même code mais adapté) que les messages "Sujets les plus commentés" de la ruelle:
![image](https://user-images.githubusercontent.com/20457917/32772202-73981e4e-c925-11e7-936f-38be6c9e3373.png)

# Longues publications
Justement, restons sur ce bloque là (dernier screen), si tu pouvais:
*N* + Dans les grands publications et sur les côtés, quand le message est coupé, mettre "..." à la fin des messages.

*Nbis* + Edit: apporter la même architecture de ces publications (que j'évoque jusqu'alors) sur la page dépêches magiques juste ici:

![image](https://user-images.githubusercontent.com/20457917/32774082-74da4c54-c92b-11e7-87f5-bb52549f3fc6.png)

# Aside et main
*O* Dans les aside apporter une class "colonne-infos" et là où se trouvent les infos, publications etc... sur toutes les pages, apporter "colonne-page". Ca va me permettre d'apporter des modifications CSS plus facilement !

# Changer de mot de passe
*P* Intégrer la page dans le profil (comme pour les publications, etc etc etc)

# Corrections grammaticales
*Q* Apporter dans la page de langue:
- "Page créé" (corriger en "page(s) créée(s)")
- Page de changement de mot de passe, changer "vérification" par "Répéter le nouveau mot de passe"
- Créer une nouvelle publication, ajouter le bouton "create" pour qu'on puisse le mettre en français

C'est énormément de choses, mais avant l'alpha j'ai fais le point sur les détails qui peuvent gêner à l'expérience utilisateur et que l'on va nous reprocher. Comme tu peux le voir, il y a des lettres: c'est pour que tu puisse me dire les modifications que tu as faite au fur et à mesure des changements. Si tu n'as pas le temps de le faire le 20, ce n'est pas grave. Mais ce sont des améliorations qui vont donner une impression de stabilité renforcé !

N'hésite pas si tu as des questions, pour ma part je crois que c'est tout ce que j'ai à dire de la plateforme à l'heure actuelle, d'où le truc mastoc !

**Comment by yunai39** [comment]
A, B, C, I, J

**Comment by yunai39** [comment]
Coucou, il y a différents points par-ci par-là que j'ai essayé de corriger comme je le pouvais, mais comme les modules n'ont pas de class spécifiques, mes modifications agissent à différents endroits non désirés. L'objectif de cette "Issue" est de renforcer une cohérence graphique au sain de la plateforme et régler quelques problèmes visuels et aussi dans l'expérience utilisateur.

Alors Marine, je suis sincèrement désolé car je suis plus que jamais très chiant et j'aime pas ça :(


*D* + Sur les pages des profils: apporter des champs Twitter, Instagram, Youtube ?
*E* + Sur les profils et pages, afficher par défaut 3 ou 4 dernières publications ?
*Ebis* + Idem, j'ajoute quelque chose: si on pouvait mettre en page les champs de modification et d'upload des images de cette manière: https://thewizardsalley.com/center/private/concept/s3/harrypotter/edit

Sur les pages:
*F* + Centraliser tous les liens dans le aside (ajouter édition de la page, édition des publications) ?
*G* + Ajouter un lien "Ajouter une publication" au dessus des publications telles que le bouton "send" quand on envoie une petite publication ?
![image](https://user-images.githubusercontent.com/20457917/32771537-406a5d40-c923-11e7-915c-03b776d092e9.png)
*H* Sur chaque lien, apporter une class de telle sorte:
![image](https://user-images.githubusercontent.com/20457917/32771660-bc64ee9c-c923-11e7-9b8a-a7ef778c6175.png)
(pareil, pour que je puisse faire agir du css)

Dans les tableaux comme celui-ci:
![image](https://user-images.githubusercontent.com/20457917/32771717-e42c3868-c923-11e7-9967-2a90aab73076.png)

Dans les formulaires:
![image](https://user-images.githubusercontent.com/20457917/32771855-6728cc7c-c924-11e7-9bb6-9f20861d9182.png)
"Title", "image", "mot de passe"... s'affichent à droite. C'est parce que j'ai mis un text-align dans la class et du coup ça bug. 
*K* + Si tu pouvais donner aux tableaux et formulaire des class spécifiques comme par exemple "class="table-form" ?

# Parlons des boutons !
Des boutons d'action se trouvent un peu partout sur le site et n'ont pas de css particulier.

Nous avons l'upload d'image dans les publications:
![image](https://user-images.githubusercontent.com/20457917/32771956-b3f4a4fe-c924-11e7-807c-6c3fdbdc1dd5.png)

Des "mettre à jour" dans à peu près tous les formulaires:
![image](https://user-images.githubusercontent.com/20457917/32771997-d2ce119e-c924-11e7-8c5c-5af763bc7314.png)

*L* +Serait-il possible d'apporter une class spécifique à ces boutons-là (même class que "send pour les courtes publications, que pour s'inscrire, pour se connecter, mettre à jour les infos, partout où se trouve un bouton d'envoie sur le site) ?

On a presque fini !

# Amélioration ergonomique des pages:
J'ai déjà créé un sujet à ce sujet, mais je le remet ici pour bien tout centraliser ! [https://github.com/yunai39/WizardsAlley/issues/88](https://github.com/yunai39/WizardsAlley/issues/88)

# Dans la messagerie
Voici cette partie de la messagerie: 
![image](https://user-images.githubusercontent.com/20457917/32772165-59b369f2-c925-11e7-9e20-65459044069a.png)

*M* + Si tu pouvais apporter la même structure (= même code mais adapté) que les messages "Sujets les plus commentés" de la ruelle:
![image](https://user-images.githubusercontent.com/20457917/32772202-73981e4e-c925-11e7-936f-38be6c9e3373.png)

# Longues publications
Justement, restons sur ce bloque là (dernier screen), si tu pouvais:
*N* + Dans les grands publications et sur les côtés, quand le message est coupé, mettre "..." à la fin des messages.

*Nbis* + Edit: apporter la même architecture de ces publications (que j'évoque jusqu'alors) sur la page dépêches magiques juste ici:

![image](https://user-images.githubusercontent.com/20457917/32774082-74da4c54-c92b-11e7-87f5-bb52549f3fc6.png)


# Aside et main
*O* Dans les aside apporter une class "colonne-infos" et là où se trouvent les infos, publications etc... sur toutes les pages, apporter "colonne-page". Ca va me permettre d'apporter des modifications CSS plus facilement !

# Changer de mot de passe
*P* Intégrer la page dans le profil (comme pour les publications, etc etc etc)

# Corrections grammaticales
*Q* Apporter dans la page de langue:
- "Page créé" (corriger en "page(s) créée(s)")
- Page de changement de mot de passe, changer "vérification" par "Répéter le nouveau mot de passe"
- Créer une nouvelle publication, ajouter le bouton "create" pour qu'on puisse le mettre en français


C'est énormément de choses, mais avant l'alpha j'ai fais le point sur les détails qui peuvent gêner à l'expérience utilisateur et que l'on va nous reprocher. Comme tu peux le voir, il y a des lettres: c'est pour que tu puisse me dire les modifications que tu as faite au fur et à mesure des changements. Si tu n'as pas le temps de le faire le 20, ce n'est pas grave. Mais ce sont des améliorations qui vont donner une impression de stabilité renforcé !

N'hésite pas si tu as des questions, pour ma part je crois que c'est tout ce que j'ai à dire de la plateforme à l'heure actuelle, d'où le truc mastoc !
