### ISSUE TITLE
Politique de confidentialité

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#94]
J'ai retrouvé ! Je te met ça ici:

`<h3>Introduction</h3>
<p>Devant le développement des nouveaux outils de communication, il est nécessaire de porter une attention particulière à la protection de la vie privée. C'est pourquoi, nous nous engageons à respecter la confidentialité des renseignements personnels que nous collectons.</p>

<h3>Conditions d'inscriptions sur la plateforme</h3>
<p>Pour la sécurité des plus jeunes, toute inscription est autorisée sur la plateforme aux personnes ayant l'âge minimum requis de 13 ans.</p>

<h3>Bonne conduite de l'utilisateur</h3>

<p>Dans le cadre de l'utilisation du Service, l'Utilisateur s'engage à :</p>
<ul>
    <li>Garantir son bon usage du Service ;</li>
    <li>Ne créer qu'un seul compte au sein du Service ;</li>
    <li>S'abstenir de saisir des informations et/ou messages, commentaires et autres contenus malveillants, dénigrants, diffamatoires, injurieux, obscènes, pornographiques, violents, à caractère raciste, xénophobe, discriminatoire, volontairement trompeurs, illicites et/ou contraires à l'ordre public ou aux bonnes mœurs ;</li>
    <li>Respecter les droits des tiers, et notamment le droit de chacun au respect de sa vie privée, de son image et de ses autres droits de la personnalité, ainsi que les droits de propriété intellectuelle (droit d'auteur, droits voisins, droit sur les bases de données, droit des marques, droit des brevets, dessins ou modèles, secret de fabrique, etc.) ;</li>
    <li>Ne pas usurper la qualité, l'attribut ou l'identifiant d'un autre Utilisateur ou d'un tiers de nature à induire en erreur ou à créer une confusion quelconque quant à son identité, à la provenance des informations, contenus (Cours, messages, commentaires, etc.) qu'il diffuse ou transmet au sein du Service ;</li>
    <li>Ne pas altérer ou perturber l'intégrité du Service et/ou des données qui y sont contenues ;</li>
    <li>Ne pas tenter d'obtenir un accès non autorisé au Service ou aux systèmes ou réseaux qui lui sont associés ou d'intercepter des données ;</li>
    <li>Utiliser le Service dans le respect des législations et réglementations nationales et/ou internationales applicables.</li>
</ul>
<p>En cas de manquement à l'une de ces obligations, OpenClassrooms se réserve le droit de suspendre temporairement ou définitivement le compte de l'Utilisateur.</p>

<h3>Signalement et/ou modération a posteriori</h3>
<p>Tout utilisateur a la possibilité de signaler à l'équipe de Wizard's Alley tout message ou commentaire et plus généralement tout contenu publié au sein du Service qui serait contraire au Contrat ou autrement illicite, et notamment outrageant, injurieux, diffamatoire, abusif, violent, obscène ou pornographique, ou comprenant une provocation à la discrimination ou à la haine fondée sur la race, la religion, le sexe, ou autre, une provocation aux crimes et délits, ou une apologie de crime, ou de nature à porter atteinte aux droit de propriété intellectuelle ou aux droits de la personnalité des tiers, ou encore de nature à altérer le fonctionnement du Service et/ou du Site, de quelque manière que ce soit.</p>
<p>L'équipe de Wizard's Alley se réserve le droit de supprimer tout contenu illicite ou non conforme au Contrat qui lui aura été préalablement signalé par tout Utilisateur. Tout signalement manifestement abusif pourra être sanctionné par l'équipe modératrice de Wizard's Alley.</p>

<h3>Collecte des renseignements personnels</h3>

<p>Nous collectons les renseignements suivants :<p>
<ul>
    <li>Nom;</li>
    <li>Prénom;</li>
    <li>Adresse électronique;</li>
    <li>Genre / Sexe;</li>
    <li>Âge / Date de naissance;</li>
    <li>Préférences (musicales, littéraires, cinématographiques, etc.);</li>
    <li>Photos et vidéos.</li>

<p>Les renseignements personnels que nous collectons sont recueillis au travers de formulaires et grâce à l'interactivité établie entre vous et notre site Web. Nous utilisons également, comme indiqué dans la section suivante, des fichiers témoins et/ou journaux pour réunir des informations vous concernant.</p>

<h3>Formulaires et interactivité sur la plateforme</h3>

<p>Vos renseignements personnels sont collectés par le biais de formulaire, à savoir :</p>
<ul>
    <li>Formulaire d'inscription au site Web;</li>
    <li>Concours.</li>
</ul>
<p>Nous utilisons les renseignements ainsi collectés pour les finalités suivantes :</p>
<ul>
    <li>Gestion du site Web (présentation, organisation)</li>
</ul>
<p>Vos renseignements sont également collectés par le biais de l'interactivité pouvant s'établir entre vous et notre site Web et ce, de la façon suivante:</p>
<ul>
    <li>Statistiques;</li>
    <li>Gestion du site Web (présentation, organisation).</li>
</ul>
<p>Nous utilisons les renseignements ainsi collectés pour les finalités suivantes :</p>
<ul>
    <li>Forum ou aire de discussion;</li>
    <li>Commentaires;</li>
    <li>Correspondance.</li>
</ul>
<h3>Droit d'opposition et de retrait</h3>

<p>Nous nous engageons à vous offrir un droit d'opposition et de retrait quant à vos renseignements personnels.
Le droit d'opposition s'entend comme étant la possiblité offerte aux internautes de refuser que leurs renseignements personnels soient utilisées à certaines fins mentionnées lors de la collecte.</p>

<p>Le droit de retrait s'entend comme étant la possiblité offerte aux internautes de demander à ce que leurs renseignements personnels ne figurent plus, par exemple, dans une liste de diffusion.</p>

<p>Pour pouvoir exercer ces droits, vous pouvez :
<ul>
    <li>Courriel : contact@thewizardsalley.com</li>
    <li>Section du site web : thewizardsalley.com</li>
    <li>Page Facebook, compte Twitter, directement sur le site internet</li>
</ul>

<h3>Droit d'accès</h3>

<p>Nous nous engageons à reconnaître un droit d'accès et de rectification aux personnes concernées désireuses de consulter, modifier, voire radier les informations les concernant.</p>
<p>L'exercice de ce droit se fera :</p>
<ul>
    <li>Courriel : contact@thewizardsalley.com</li>
    <li>Section du site web : thewizardsalley.com</li>
    <li>Page Facebook, compte Twitter, directement sur le site internet</li>
</ul>

<p>Les renseignements personnels que nous collectons sont conservés dans un environnement sécurisé. Les personnes travaillant pour nous sont tenues de respecter la confidentialité de vos informations.</p>
<p>Pour assurer la sécurité de vos renseignements personnels, nous avons recours aux mesures suivantes :</p>
<ul>
    <li>Protocole SSL (Secure Sockets Layer)</li>
    <li>Gestion des accès - personne autorisée</li>
    <li>Gestion des accès - personne concernée</li>
    <li>Sauvegarde informatique</li>
    <li>Identifiant / mot de passe</li>
    <li>Pare-feu (Firewalls)</li>
</ul>
<p>Nous nous engageons à maintenir un haut degré de confidentialité en intégrant les dernières innovations technologiques permettant d'assurer la confidentialité de vos transactions. Toutefois, comme aucun mécanisme n'offre une sécurité maximale, une part de risque est toujours présente lorsque l'on utilise Internet pour transmettre des renseignements personnels.</p>

<h3>Intteruption de Wizard's Alley pour maintenance ou améliorations</h3>

<p>L'équipe de Wizard's Alley s'engage à mettre tout en œuvre pour assurer le bon fonctionnement du Service et son accessibilité par l'Utilisateur mais elle n'est tenue qu'à une obligation de moyens concernant la continuité de l'accès au Service.</p>
<p>Wizard's Alley ne garantit pas la pérennité ou les performances du Service.</p>

<p>Wizard's Alley se réserve le droit de suspendre, sans préavis, l'accès au Service, temporairement ou définitivement.</p>

<p>Wizard's Alley pourra interrompre l'accès au Service pour des raisons notamment de maintenance, de mise à jour et en cas d'urgence.</p>

<p>L'interruption temporaire ou définitive du Service n'engagera pas la responsabilité de Wizard's Alley et ne donnera droit à aucune indemnité à l'Utilisateur.</p>

<p>Pour éviter autant que possible des désagréments, l'Utilisateur doit s'assurer de la réalisation régulière de sauvegardes concernant ses informations, contenus et logiciels.</p>

<p>L'Utilisateur reconnait utiliser le Service tel qu'il lui est fourni, à ses risques et périls et ce, en parfaite connaissance de cause. </p>

<h3>Législation</h3>

<p>Nous nous engageons à respecter les dispositions législatives énoncées dans les loies Françaises.</p>`

**Comment by yunai39** [comment]
c'est en place par contre je me demande si c'est pas les metion legale et la politique de confidentialite ?

**Comment by mxchrles** [comment]
Non car il manque toute la partie hébergeur etc ^^
