### ISSUE TITLE
Nouvelle maquette affichage des publications

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#98]
Ayant réfléchi, c'est peut-être lourd à afficher les publications dans les pages. Il faut scroller, on ne sait pas si on est sur le profil ou sur la publication... Bref, c'était mieux avant. Super Maxime de faire chier Marine à intégrer les publications dans les pages sur 3 issues différentes ! J'ai merdé :(

Voici un concept, qu'en dis-tu ? :) https://thewizardsalley.com/center/private/concept/publication/

**Comment by yunai39** [comment]
J'ai fais les modifications, du coup il reste le titre a refaire un peut j'ai deja ajouter les classes pour le css
