### ISSUE TITLE
Impossible d'uploader image profil + couverture + dans les publications

### ISSUE THREAD

**Issue by mxchrles** [yunai39/WizardsAlley#99]
Mika me rapporte qu'il ne peux pas modifier son image de profil.
Pour ma part impossible d'intégrer une image dans les publications (trop grande). C'est quoi la taille maximale pour une image ? Serait-il possible de spécifier les tailles maximales des images à côté de chaque légende ? Et si la taille est trop grande, au lieu d'envoyer vers une page d'erreur est-il possible de le notifier (comme si c'était une validation de publication, ou que l'amitié a été ajouté etc) ?

![image](https://user-images.githubusercontent.com/20457917/33012598-bca9c018-cde1-11e7-813e-74ee93382063.png)

**Comment by yunai39** [comment]
Pourtant c'est marque en clair l'image est limite a 400px, apres c'est volontaire que j'ai limiter la taille des image, j'ai pas 100 go sur mon raspberry et je risque d'etre limiter un moment en bade passantes, je vais juste rajouter un message affichant clairement la limite du taille de l'image
